INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 1, 1, '사우나', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 2, 3, '요가', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 3, 3, '헬스', '사우나', '밀론프로그램', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 4, 2, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 5, 2, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 5, 15, '개인PT', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 6, 1, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 6, 10, 'PT', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 7, 1, '헬스', 'GX', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 8, 1, '헬스', 'GX', '사우나', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 9, 1.5, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 10, 1, '헬스', '스피닝', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 11, 1, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 12, 2.5, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 13, 4, '눈썹', '겨드랑이왁싱', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 13, 4.5, '내츄럴 속눈썹', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 13, 14, '브라질리언왁싱', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 14, 4, '스크린 테니스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 15, 4.5, '기본케어', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 15, 11, '젤네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 15, 14, '속눈썹연장', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 16, 20, '집중케어', '트러블', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 16, 10, '트러블케어', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 17, 9, '목', '허리', '골반', '체형관리', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 17, 18, '목', '어깨', '허리', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 18, 7, '댄스', '룸바', '살사', '퀵스텝', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 19, 1.5, '탁구', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 20, 5.5, '크로스핏', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 21, 2, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 22, 2, '왁싱', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 22, 9, '속눈썹', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 22, 10, '젤네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 23, 4, '킥복싱', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 24, 2, '골프', '사우나', '자유수영', '헬스', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 25, 3, '요가', '필라테스', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 25, 10, 'PT', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 26, 1, '사우나', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 27, 4.5, '기본케어', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 27, 11, '젤네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 27, 14, '속눈썹연장', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 28, 1, '헬스', '골프', '사우나', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 29, 2, '체조명상호흡', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 30, 4, '기본케어', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 30, 12, '젤네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 31, 1, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 32, 2, '마사지', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 33, 8, '기구필라테스8:1', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 34, 3, '기본케어(손)', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 34, 4.5, '커트', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 34, 9, '속눈썹50%', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 34, 12, '젤네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 34, 12, '뿌리염색', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 34, 15, '베이직펌', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 35, 4.5, '기본케어', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 35, 11, '젤네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 35, 14, '속눈썹연장', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 36, 2, '마사지', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 37, 2, '사우나', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 38, 1.5, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 39, 1, '헬스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 40, 2.5, '골프', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 41, 2, '점핑', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 42, 7.5, '마사지', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 43, 9.5, '필라테스', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 44, 3, '기본네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 44, 11, '젤네일', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 45, 2, '탁구', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 46, 3, '복싱', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 47, 3, '검도(50분)', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 47, 4.5, '검도(2시간)', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 48, 3.5, '주짓수', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 49, 3, '크로스핏(07:30 ~ 10:29)', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 49, 4, '크로스핏(20:40 ~ 21:50)', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 49, 4, '크로스핏(12:30 ~ 17:29)', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 49, 5, '크로스핏(18:20 ~ 19:30)', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 50, 7.5, '왁싱', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 50, 13.5, '속눈썹', '', '', '', '', '' );
INSERT INTO CONTENT_LIST VALUES(content_idx.nextval, 50, 13.5, '젤네일', '', '', '', '', '' );

commit;